---
version: "3.2"
services:
  shush:
    image: realestate/shush:1.3.4
    working_dir: /app
    volumes:
      - $HOME/.aws:/root/.aws
      - ./app:/app

  stackup:
    image: realestate/stackup:latest
    working_dir: /app
    volumes:
      - $HOME/.aws:/root/.aws
      - .:/app
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1

  aws:
    image: cgswong/aws:aws
    working_dir: /app
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws

  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 10s
      retries: 3
